# .travis.yml
language: node_js
node_js: node
sudo: required
before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
branches:
  only:
    - develop
cache:
  yarn: true
script:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - cd website
  - yarn install
  - GIT_USER="${GH_NAME}" CURRENT_BRANCH=master yarn run publish-gh-pages
notifications:
  email: "${GH_EMAIL}"
  on_success: always
  on_failure: always