---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: website/blog
  label: Articles
  create: all
  match: "**/*"
- type: directory
  path: docs/demo
  label: Demo
  create: all
  match: "**/*"
upload_dir: website
public_path: "/website/static"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: build
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv/website"
  instant_preview_command: npm run start -- --port 8080
