name: Failsafe Page Generation
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # every day 06:00, 18:00 GMT+8
    - cron: '0 10,22 * * *'

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

jobs:
  wait-for-deployment:
    uses: dazedbear/dazedbear.github.io/.github/workflows/vercel-deployment.yml@main
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

  failsafe-generation-stage:
    name: Failsafe Page Generation Stage
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/pull')
    needs: wait-for-deployment
    env:
      NEXT_PUBLIC_APP_ENV: stage
    steps:
      - name: Checkout project source
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependency
        run: npm install --legacy-peer-deps
      - name: Run failsafe generation
        run: npm run task:failsafe

  failsafe-generation-production:
    name: Failsafe Page Generation Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: wait-for-deployment
    env:
      NEXT_PUBLIC_APP_ENV: production
    steps:
      - name: Checkout project source
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependency
        run: npm install --legacy-peer-deps
      - name: Run failsafe generation
        run: npm run task:failsafe
