name: Failsafe
on:
  schedule:
    # every day 06:00, 18:00 GMT+8
    - cron: '0 10,22 * * *'

jobs:
  failsafe-generation:
    name: Failsafe Page Generation
    runs-on: ubuntu-latest
    steps:
      # Checkout project source
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependency
        run: npm install --legacy-peer-deps
      - name: Run failsafe generation
        run: npm run task:failsafe
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
