name: Release Note
on:
  push:
    branches: [main]
permissions:
  contents: write

jobs:
  release:
    name: Release Note
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - name: Checkout project source
        uses: actions/checkout@v3
      - name: Install dependency
        run: npm ci
      - name: Release Note
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
